### ISSUE TITLE
HW: MP157

### ISSUE THREAD

**Issue by kimstik** [speedcontrols/ac_sc_grinder#7]
I'm afraid the MP157 is not pin compatible with the LNK3204.

Few more notes:
It is better to indicate that C7 is rated for at least 400 V.
I may [not recommend](https://www.mikrocontroller.net/search?query=LNK304+defekt) to use LNK30x.
You can also look at the [RL10](https://ww1.microchip.com/downloads/en/DeviceDoc/SR10%20B080613.pdf) as coil-free way.

**Comment by puzrin** [comment]
That's all in the past.

1. MP157 has a separate PCB version and is not recommended to use due to bad availability
2. Latest PCB should use LNK320x. The schematic has appropriate notes. 
3. Coil-free chips have a big turn-on time (several seconds) or wrong current/size, depending on the stabilization method, that's not acceptable for the concrete use case.

Also, I'd like to point out that this project is quite old. The new one is https://github.com/speedcontrols/dc_sc_grinder, but it still has no working firmware (draft only).

**Comment by kimstik** [comment]
> That's all in the past.
> 
> 1. MP157 has a separate PCB version and is not recommended to use due to bad availability
> 2. Latest PCB should use LNK320x. The schematic has appropriate notes.
> 3. Coil-free chips have a big turn-on time (several seconds) or wrong current/size, depending on the stabilization method, that's not acceptable for the concrete use case.
> 
> Also, I'd like to point out that this project is quite old. The new one is https://github.com/speedcontrols/dc_sc_grinder, but it still has no working firmware (draft only).

My point to upgrade old Hilda with working solution. 

MP157 stuff is not so clear:
[/doc/development.md](https://github.com/speedcontrols/ac_sc_grinder/blob/8f356d63a9e19cb0ab96740df264dba7830b99a6/doc/development.md)
```
LNK3204 replacement
You can use LNK304 or MP157, but you should update feedback resistors (according to chip datasheet) to make output 4.0-4.2 volts.
```

Description/schematics mismatch here:
https://oshwlab.com/speed/ac-speed-control-v2-dev

[dc_sc_grinder](https://github.com/speedcontrols/dc_sc_grinder) have same issue of "non-marking" voltage rating of HV caps.
It can be confusing for newbies.
